name: Remove labels
on:
  issues:
    types:
      - closed
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Remove labels
        uses: andymckay/labeler@1.0.2
        with:
          remove-labels: "priority"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
